BitqueryLogger.init(type: :tcp, **BITQUERY_LOGGER_CONFIG)

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  # config.ignored_exceptions += %w{ActionView::TemplateError CustomError}

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  # config.ignore_if do |exception, options|
  # !Rails.env.production?
  # end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

end

ExceptionNotifier::Rake.configure

Rails.application.config.middleware.use ExceptionNotification::Rack,
                                        tcp: {}

Rails.application.config.middleware.use BitqueryLogger::BitqueryLoggerMiddleware
