BITQUERY_PROJECT_URL = ENV.fetch('BITQUERY_PROJECT_URL', nil)
BITQUERY_IMAGES = ENV.fetch('BITQUERY_IMAGES', nil)
BITQUERY_GRAPHQL = ENV.fetch('BITQUERY_GRAPHQL', nil)
BITQUERY_STREAMING = ENV.fetch('BITQUERY_STREAMING', nil)
BITQUERY_IDE_API = ENV.fetch('BITQUERY_IDE_API', nil)
EXPLORER_URL = ENV.fetch('EXPLORER_URL', nil)
ANALYTICS = ENV['ANALYTICS'] == 'true'
BITQUERY_STREAMING_GRAPHQL = ENV.fetch('BITQUERY_STREAMING_GRAPHQL', nil)
