BITQUERY_PROJECT_URL = ENV['BITQUERY_PROJECT_URL']
BITQUERY_IMAGES = ENV['BITQUERY_IMAGES']
BITQUERY_GRAPHQL = ENV['BITQUERY_GRAPHQL']
BITQUERY_IDE_API = ENV['BITQUERY_IDE_API']
EXPLORER_URL = ENV['EXPLORER_URL']
ANALYTICS = ENV['ANALYTICS']=='true'
BITQUERY_STREAMING_GRAPHQL=ENV['BITQUERY_STREAMING_GRAPHQL']
