BITQUERY_WIDGETS_URL = ENV['BITQUERY_WIDGETS_URL']
BITQUERY_PROJECT_URL = ENV['BITQUERY_PROJECT_URL']
BITQUERY_IMAGES = ENV['BITQUERY_IMAGES']
BITQUERY_GRAPHQL = ENV['BITQUERY_GRAPHQL']
ANALYTICS = ENV['ANALYTICS']=='true'